        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: awskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: awssecret
        - name: DB_HOST
          value: postgres-master
        - name: DB_NAME
          value: postgres
        - name: DISABLE_DEBUG
          value: "1"
        - name: GLOBAL_MODEL
          value: "1"
        - name: ENABLE_CLOUDFS
          value: "1"
        - name: DOCKER_MODE
          value: "true"
        - name: MEDIA_BUCKET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: mediabucket
        - name: MEDIA_URL
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: mediaurl
        - name: RABBIT_HOST
          value: rabbitmq-master
        - name: KUBE_MODE
          value: "1"
        - name: RABBIT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitusername
        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitpassword
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secretkey
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbusername
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbpassword
        - name: CLOUD_FS_PREFIX
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: cloudfsprefix
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redishost
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redispassword
        - name: INIT_PROCESS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: initprocess
        - name: INIT_MODELS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: initmodels