sudo: required

language: python

python:
  - "2.7"

services:
  - docker
  - postgresql
  - rabbitmq
  - redis-server

addons:
  postgresql: "9.6"

virtualenv:
  system_site_packages: true

env:
  global:
    - AUTH_DISABLED=1
    - SECRET_KEY=123213123123213213
    - LAUNCH_BY_NAME_indexer_inception=1
    - LAUNCH_BY_NAME_retriever_inception=1
    - LAUNCH_BY_NAME_detector_coco=1
    - TRAVISTEST=1
    - INIT_MODELS=WwogIHsKICAgICJtb2RlbF90eXBlIjogIkQiLAogICAgIm5hbWUiOiAiY29jbyIsCiAgICAiZGV0ZWN0b3JfdHlwZSI6ICJUIiwKICAgICJhbGdvcml0aG0iOiAibW9iaWxlbmV0X3NzZCIsCiAgICAiZmlsZW5hbWUiOiAiY29jb19tb2JpbGVuZXQucGIiLAogICAgImZpbGVzIjogWwogICAgICB7CiAgICAgICAgInVybCI6ICJodHRwczovL3d3dy5kcm9wYm94LmNvbS9zL256ejI2YjJwNHd4eWdnMy9jb2NvX21vYmlsZW5ldC5wYiIsCiAgICAgICAgImZpbGVuYW1lIjogImNvY29fbW9iaWxlbmV0LnBiIgogICAgICB9CiAgICBdLAogICAgIm1vZGUiOiAiVCIsCiAgICAiYXJndW1lbnRzIjogewogICAgICAiY2xhc3NfaW5kZXhfdG9fc3RyaW5nIjogewogICAgICAgICIxIjogInBlcnNvbiIsCiAgICAgICAgIjIiOiAiYmljeWNsZSIsCiAgICAgICAgIjMiOiAiY2FyIiwKICAgICAgICAiNCI6ICJtb3RvcmN5Y2xlIiwKICAgICAgICAiNSI6ICJhaXJwbGFuZSIsCiAgICAgICAgIjYiOiAiYnVzIiwKICAgICAgICAiNyI6ICJ0cmFpbiIsCiAgICAgICAgIjgiOiAidHJ1Y2siLAogICAgICAgICI5IjogImJvYXQiLAogICAgICAgICIxMCI6ICJ0cmFmZmljIGxpZ2h0IiwKICAgICAgICAiMTEiOiAiZmlyZSBoeWRyYW50IiwKICAgICAgICAiMTMiOiAic3RvcCBzaWduIiwKICAgICAgICAiMTQiOiAicGFya2luZyBtZXRlciIsCiAgICAgICAgIjE1IjogImJlbmNoIiwKICAgICAgICAiMTYiOiAiYmlyZCIsCiAgICAgICAgIjE3IjogImNhdCIsCiAgICAgICAgIjE4IjogImRvZyIsCiAgICAgICAgIjE5IjogImhvcnNlIiwKICAgICAgICAiMjAiOiAic2hlZXAiLAogICAgICAgICIyMSI6ICJjb3ciLAogICAgICAgICIyMiI6ICJlbGVwaGFudCIsCiAgICAgICAgIjIzIjogImJlYXIiLAogICAgICAgICIyNCI6ICJ6ZWJyYSIsCiAgICAgICAgIjI1IjogImdpcmFmZmUiLAogICAgICAgICIyNyI6ICJiYWNrcGFjayIsCiAgICAgICAgIjI4IjogInVtYnJlbGxhIiwKICAgICAgICAiMzEiOiAiaGFuZGJhZyIsCiAgICAgICAgIjMyIjogInRpZSIsCiAgICAgICAgIjMzIjogInN1aXRjYXNlIiwKICAgICAgICAiMzQiOiAiZnJpc2JlZSIsCiAgICAgICAgIjM1IjogInNraXMiLAogICAgICAgICIzNiI6ICJzbm93Ym9hcmQiLAogICAgICAgICIzNyI6ICJzcG9ydHMgYmFsbCIsCiAgICAgICAgIjM4IjogImtpdGUiLAogICAgICAgICIzOSI6ICJiYXNlYmFsbCBiYXQiLAogICAgICAgICI0MCI6ICJiYXNlYmFsbCBnbG92ZSIsCiAgICAgICAgIjQxIjogInNrYXRlYm9hcmQiLAogICAgICAgICI0MiI6ICJzdXJmYm9hcmQiLAogICAgICAgICI0MyI6ICJ0ZW5uaXMgcmFja2V0IiwKICAgICAgICAiNDQiOiAiYm90dGxlIiwKICAgICAgICAiNDYiOiAid2luZSBnbGFzcyIsCiAgICAgICAgIjQ3IjogImN1cCIsCiAgICAgICAgIjQ4IjogImZvcmsiLAogICAgICAgICI0OSI6ICJrbmlmZSIsCiAgICAgICAgIjUwIjogInNwb29uIiwKICAgICAgICAiNTEiOiAiYm93bCIsCiAgICAgICAgIjUyIjogImJhbmFuYSIsCiAgICAgICAgIjUzIjogImFwcGxlIiwKICAgICAgICAiNTQiOiAic2FuZHdpY2giLAogICAgICAgICI1NSI6ICJvcmFuZ2UiLAogICAgICAgICI1NiI6ICJicm9jY29saSIsCiAgICAgICAgIjU3IjogImNhcnJvdCIsCiAgICAgICAgIjU4IjogImhvdCBkb2ciLAogICAgICAgICI1OSI6ICJwaXp6YSIsCiAgICAgICAgIjYwIjogImRvbnV0IiwKICAgICAgICAiNjEiOiAiY2FrZSIsCiAgICAgICAgIjYyIjogImNoYWlyIiwKICAgICAgICAiNjMiOiAiY291Y2giLAogICAgICAgICI2NCI6ICJwb3R0ZWQgcGxhbnQiLAogICAgICAgICI2NSI6ICJiZWQiLAogICAgICAgICI2NyI6ICJkaW5pbmcgdGFibGUiLAogICAgICAgICI3MCI6ICJ0b2lsZXQiLAogICAgICAgICI3MiI6ICJ0diIsCiAgICAgICAgIjczIjogImxhcHRvcCIsCiAgICAgICAgIjc0IjogIm1vdXNlIiwKICAgICAgICAiNzUiOiAicmVtb3RlIiwKICAgICAgICAiNzYiOiAia2V5Ym9hcmQiLAogICAgICAgICI3NyI6ICJjZWxsIHBob25lIiwKICAgICAgICAiNzgiOiAibWljcm93YXZlIiwKICAgICAgICAiNzkiOiAib3ZlbiIsCiAgICAgICAgIjgwIjogInRvYXN0ZXIiLAogICAgICAgICI4MSI6ICJzaW5rIiwKICAgICAgICAiODIiOiAicmVmcmlnZXJhdG9yIiwKICAgICAgICAiODQiOiAiYm9vayIsCiAgICAgICAgIjg1IjogImNsb2NrIiwKICAgICAgICAiODYiOiAidmFzZSIsCiAgICAgICAgIjg3IjogInNjaXNzb3JzIiwKICAgICAgICAiODgiOiAidGVkZHkgYmVhciIsCiAgICAgICAgIjg5IjogImhhaXIgZHJpZXIiLAogICAgICAgICI5MCI6ICJ0b290aGJydXNoIgogICAgICB9CiAgICB9CiAgfSwKICB7CiAgICAibW9kZWxfdHlwZSI6ICJEIiwKICAgICJuYW1lIjogInRleHRib3giLAogICAgImZpbGVzIjogWwogICAgICB7CiAgICAgICAgInVybCI6ICJodHRwczovL3d3dy5kcm9wYm94LmNvbS9zL2doeG93ZHVhNjVyODJkNi9jaGVja3BvaW50IiwKICAgICAgICAiZmlsZW5hbWUiOiAiY2hlY2twb2ludCIKICAgICAgfSwKICAgICAgewogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly93d3cuZHJvcGJveC5jb20vcy92OXc0bWhja3M3YTcxOWsvVkdHbmV0X2Zhc3RfcmNubl9pdGVyXzUwMDAwLmNrcHQuZGF0YS0wMDAwMC1vZi0wMDAwMSIsCiAgICAgICAgImZpbGVuYW1lIjogIlZHR25ldF9mYXN0X3Jjbm5faXRlcl81MDAwMC5ja3B0LmRhdGEtMDAwMDAtb2YtMDAwMDEiCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAidXJsIjogImh0dHBzOi8vd3d3LmRyb3Bib3guY29tL3MvMmQwbGljeThucHlwZTZyL1ZHR25ldF9mYXN0X3Jjbm5faXRlcl81MDAwMC5ja3B0LmluZGV4IiwKICAgICAgICAiZmlsZW5hbWUiOiAiVkdHbmV0X2Zhc3RfcmNubl9pdGVyXzUwMDAwLmNrcHQuaW5kZXgiCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAidXJsIjogImh0dHBzOi8vd3d3LmRyb3Bib3guY29tL3MvdndtejJyYTlqb3ZseGpkL1ZHR25ldF9mYXN0X3Jjbm5faXRlcl81MDAwMC5ja3B0Lm1ldGEiLAogICAgICAgICJmaWxlbmFtZSI6ICJWR0duZXRfZmFzdF9yY25uX2l0ZXJfNTAwMDAuY2twdC5tZXRhIgogICAgICB9CiAgICBdLAogICAgImFsZ29yaXRobSI6ICJDVFBOIiwKICAgICJtb2RlIjogIlQiCiAgfSwKICB7CiAgICAibW9kZWxfdHlwZSI6ICJEIiwKICAgICJuYW1lIjogImZhY2UiLAogICAgInVybCI6IG51bGwsCiAgICAiZmlsZW5hbWUiOiBudWxsLAogICAgImFsZ29yaXRobSI6ICJtdGNubl9mYWNlbmV0IiwKICAgICJtb2RlIjogIlQiCiAgfSwKICB7CiAgICAibW9kZWxfdHlwZSI6ICJJIiwKICAgICJuYW1lIjogImluY2VwdGlvbiIsCiAgICAiZmlsZW5hbWUiOiAibmV0d29yay5wYiIsCiAgICAiZmlsZXMiOiBbCiAgICAgIHsKICAgICAgICAidXJsIjogImh0dHBzOi8vd3d3LmRyb3Bib3guY29tL3MvZmM3bGkydnduOGx2c3l1L25ldHdvcmsucGIiLAogICAgICAgICJmaWxlbmFtZSI6ICJuZXR3b3JrLnBiIgogICAgICB9CiAgICBdLAogICAgImFyZ3VtZW50cyI6IHsKICAgICAgImNvbXBvbmVudHMiOiAyMDQ4CiAgICB9LAogICAgInNoYXN1bSI6ICI0OGIwMjZjZjc3ZGZiZDVkOTg0MWNjYTNlZTU1MGVmMGVlNWEwNzUxIiwKICAgICJtb2RlIjogIlQiCiAgfSwKICB7CiAgICAibW9kZWxfdHlwZSI6ICJJIiwKICAgICJuYW1lIjogImZhY2VuZXQiLAogICAgImZpbGVzIjogWwogICAgICB7CiAgICAgICAgInVybCI6ICJodHRwczovL3d3dy5kcm9wYm94LmNvbS9zL2p5dHBndzhldDA5ZWRlOS9mYWNlbmV0LnBiIiwKICAgICAgICAiZmlsZW5hbWUiOiAiZmFjZW5ldC5wYiIKICAgICAgfQogICAgXSwKICAgICJhcmd1bWVudHMiOiB7CiAgICAgICJjb21wb25lbnRzIjogMTI4CiAgICB9LAogICAgInNoYXN1bSI6ICI5Zjk5Y2FjY2JjNzVkY2VlOGNiMGE1NWEwNTUxZDdjNWNiOGE2ODM2IiwKICAgICJtb2RlIjogIlQiCiAgfSwKICB7CiAgICAibW9kZWxfdHlwZSI6ICJBIiwKICAgICJuYW1lIjogImNybm4iLAogICAgImZpbGVzIjogWwogICAgICB7CiAgICAgICAgInVybCI6ICJodHRwczovL3d3dy5kcm9wYm94LmNvbS9zL2wwdm84M2htdnYyYWlwbi9jcm5uLnB0aCIsCiAgICAgICAgImZpbGVuYW1lIjogImNybm4ucHRoIgogICAgICB9CiAgICBdLAogICAgIm1vZGUiOiAiUCIKICB9LAogIHsKICAgICJtb2RlbF90eXBlIjogIkEiLAogICAgIm5hbWUiOiAidGFnZ2VyIiwKICAgICJmaWxlcyI6IFsKICAgICAgewogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly93d3cuZHJvcGJveC5jb20vcy91bW8weHRsam05YW45MHgvb3Blbl9pbWFnZXMuY2twdCIsCiAgICAgICAgImZpbGVuYW1lIjogIm9wZW5faW1hZ2VzLmNrcHQiCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAidXJsIjogImh0dHBzOi8vd3d3LmRyb3Bib3guY29tL3MvZjkzYXhkdGxiM2x0ajQwL29wZW5faW1hZ2VzLmNrcHQubWV0YSIsCiAgICAgICAgImZpbGVuYW1lIjogIm9wZW5faW1hZ2VzLmNrcHQubWV0YSIKICAgICAgfSwKICAgICAgewogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly93d3cuZHJvcGJveC5jb20vcy8yc2Q1bnpweWhzajEwdzUvb3Blbl9pbWFnZXNfbGFiZWxtYXAudHh0IiwKICAgICAgICAiZmlsZW5hbWUiOiAib3Blbl9pbWFnZXNfbGFiZWxtYXAudHh0IgogICAgICB9LAogICAgICB7CiAgICAgICAgInVybCI6ICJodHRwczovL3d3dy5kcm9wYm94LmNvbS9zL3lib3F2NGxlZW02b3kwMS9vcGVuX2ltYWdlc19kaWN0LmNzdiIsCiAgICAgICAgImZpbGVuYW1lIjogIm9wZW5faW1hZ2VzX2RpY3QuY3N2IgogICAgICB9CiAgICBdLAogICAgIm1vZGUiOiAiVCIKICB9LAogIHsKICAgICJmaWxlcyI6IFsKICAgICAgewogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly93d3cuZHJvcGJveC5jb20vcy9ibXVvMHZoZnRmOGhpMjcvbW9kZWwucHJvdG8iLAogICAgICAgICJmaWxlbmFtZSI6ICJtb2RlbC5wcm90byIKICAgICAgfSwKICAgICAgewogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly93d3cuZHJvcGJveC5jb20vcy9xYW5qOGxlOHIzYWhzNW0vbW9kZWwuUC5ucHkiLAogICAgICAgICJmaWxlbmFtZSI6ICJtb2RlbC5QLm5weSIKICAgICAgfSwKICAgICAgewogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly93d3cuZHJvcGJveC5jb20vcy9iMnlhZWM5N2xoa2Vqb2EvbW9kZWwubXUubnB5IiwKICAgICAgICAiZmlsZW5hbWUiOiAibW9kZWwubXUubnB5IgogICAgICB9LAogICAgICB7CiAgICAgICAgInVybCI6ICJodHRwczovL3d3dy5kcm9wYm94LmNvbS9zL3plZTNvMTJkendqOHpydi9tb2RlbC5wY2EucGtsIiwKICAgICAgICAiZmlsZW5hbWUiOiAibW9kZWwucGNhLnBrbCIKICAgICAgfSwKICAgICAgewogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly93d3cuZHJvcGJveC5jb20vcy95NGJoOTRwMjU0Ymgxa2wvbW9kZWwucGVybWluZC5wa2wiLAogICAgICAgICJmaWxlbmFtZSI6ICJtb2RlbC5wZXJtaW5kLnBrbCIKICAgICAgfQogICAgXSwKICAgICJuYW1lIjogIkZhY2VuZXRfTE9QUV9vbl9MRlciLAogICAgImFsZ29yaXRobSI6ICJMT1BRIiwKICAgICJhcmd1bWVudHMiOiB7CiAgICAgICJpbmRleGVyX3NoYXN1bSI6ICI5Zjk5Y2FjY2JjNzVkY2VlOGNiMGE1NWEwNTUxZDdjNWNiOGE2ODM2IiwKICAgICAgIm0iOiAzMiwKICAgICAgInN1YiI6IDI1NiwKICAgICAgImNvbXBvbmVudHMiOiA2NCwKICAgICAgInYiOiAzMgogICAgfSwKICAgICJtb2RlbF90eXBlIjogIlAiLAogICAgInNoYXN1bSI6ICI5M2JlMmY5OWQ0MzJhN2NlMmQxNjI2MTA3NjU5NTEwNzU1ZWEzODE1IgogIH0sCiAgewogICAgImZpbGVzIjogWwogICAgICB7CiAgICAgICAgInVybCI6ICJodHRwczovL3d3dy5kcm9wYm94LmNvbS9zLzc3a210MjBqbmgzMWpzZC9laWdlbnZhbHMubnB5IiwKICAgICAgICAiZmlsZW5hbWUiOiAiZWlnZW52YWxzLm5weSIKICAgICAgfSwKICAgICAgewogICAgICAgICJ1cmwiOiAiaHR0cHM6Ly93d3cuZHJvcGJveC5jb20vcy85MjVvbDN5MzA4czJpaTUvZWlnZW52ZWNzLm5weSIsCiAgICAgICAgImZpbGVuYW1lIjogImVpZ2VudmVjcy5ucHkiCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAidXJsIjogImh0dHBzOi8vd3d3LmRyb3Bib3guY29tL3MvNG9tOG5jZ3pnMGQxdml4L21lYW4ubnB5IiwKICAgICAgICAiZmlsZW5hbWUiOiAibWVhbi5ucHkiCiAgICAgIH0KICAgIF0sCiAgICAibmFtZSI6ICJJbmNlcHRpb25fUENBX2Zyb21fWW91dHViZThNIiwKICAgICJhbGdvcml0aG0iOiAiUENBIiwKICAgICJhcmd1bWVudHMiOiB7CiAgICAgICJpbmRleGVyX3NoYXN1bSI6ICI0OGIwMjZjZjc3ZGZiZDVkOTg0MWNjYTNlZTU1MGVmMGVlNWEwNzUxIiwKICAgICAgImNvbXBvbmVudHMiOiAxMDI0CiAgICB9LAogICAgIm1vZGVsX3R5cGUiOiAiUCIsCiAgICAic2hhc3VtIjogIjg2Njg5NDMyYWMwOWQ4NmRkOTVkN2QzZWQ1NzIyN2QyN2ViMDljODEiCiAgfQpdCgo=
    - export BLASLDFLAGS="/usr/lib/libopenblas.so.0"

before_install:
  - sudo apt-get -qq update
  - wget https://www.dropbox.com/s/bjyzb8hytdwp2tp/ffmpeg-release-64bit-static.tar.xz && tar xvfJ ffmpeg-release-64bit-static.tar.xz
  - shasum ffmpeg-release-64bit-static.tar.xz | awk '$1!="a93bce9e510afef02f7e2592f6b5d117dcd08854"{exit 1}'
  - sudo mv ffmpeg*/* /bin/
  - sudo apt-get -qq install -y pkg-config python-dev unzip swig swig3.0 libopenblas-dev liblapack-dev libopencv-dev libhdf5-dev python-pip libav-tools libjpeg-dev  libpng-dev  libtiff-dev  libjasper-dev  python-numpy python-scipy  python-pycurl  python-opencv
  - sudo dpkg -L python-opencv
  - sudo wget --quiet https://yt-dl.org/downloads/latest/youtube-dl -O /bin/youtube-dl
  - sudo chmod a+rx /bin/youtube-dl
  - youtube-dl -U
  - pip install -q --only-binary=numpy,scipy numpy scipy
  - pip install -q https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.8.0-cp27-none-linux_x86_64.whl
  - pip install -q --no-deps keras
  - pip install -q --no-deps h5py
  - pip install -q --no-cache-dir http://download.pytorch.org/whl/cpu/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl
  - pip install -q torchvision
  - pwd
  - ls -lh ~/
  - ls -lh ~/AKSHAYUBHAT/DeepVideoAnalytics/
  - git clone --recursive https://github.com/facebookresearch/faiss && cd faiss && git reset --hard cdc5a8b7b876fb636362c724f54e06fe889e3ac7 && git apply ~/AKSHAYUBHAT/DeepVideoAnalytics/deploy/dockerfiles/faiss.patch && ./configure && sudo make -j $(nproc) && sudo make install && sudo make py && cd ..
#  - mkdir -p dlib && git clone https://github.com/davisking/dlib.git dlib/ && cd  dlib/ && python setup.py install --yes USE_AVX_INSTRUCTIONS && cd ..
  - sudo curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

install: "pip install -q -r requirements.txt > /dev/null"


before_script:
  - mkdir ~/media
  - export PYTHONPATH="${PYTHONPATH}:../faiss/python/"
  - export PYTHONPATH="${PYTHONPATH}:repos/"
  - export PYTHONPATH="${PYTHONPATH}:repos/tf_ctpn_cpu/"
  - cd repos/lopq/python && python setup.py install && cd ../../..
  - cd repos/tf_ctpn_cpu/lib/utils && ./make.sh && cd ../../../..
  - cd server && ./migrate.sh && cd ..
  - cd tests/data && wget --quiet https://www.dropbox.com/s/t4bgkh2w2ow8o10/WorldIsNotEnough.mp4 && cd ../..
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - cd server && python manage.py runserver 8000 &
  - cp tests/data/test_config.json config.json


script:
  - cd server && ./init_fs.py && cd ..
  - cd tests && python test_ci.py && python test_ci_face.py && cd ..
  - cd server && ./launch_from_env.py && cd ..
  - cd tests && python test_ci_search.py && cd ..
  - cd server && python scripts/generate_testing_token.py && cp creds.json ../ && cd ..
  - python tests/test_ci_client.py
  - wget --quiet localhost:8000
  - wget --quiet localhost:8000/videos/
  - wget --quiet localhost:8000/queries/
  - wget --quiet localhost:8000/queries/1/
  - wget --quiet localhost:8000/tasks/
  - wget --quiet localhost:8000/retrievers/
  - wget --quiet localhost:8000/textsearch/
  - wget --quiet localhost:8000/models/
  - wget --quiet localhost:8000/indexes/
  - wget --quiet localhost:8000/api/users/
  - wget --quiet localhost:8000/api/videos/
  - wget --quiet localhost:8000/api/tubes/
  - wget --quiet localhost:8000/api/frames/
  - wget --quiet localhost:8000/api/regionrelations/
  - wget --quiet localhost:8000/api/tuberelations/
  - wget --quiet localhost:8000/api/tuberegionrelations/
  - wget --quiet localhost:8000/api/segments/
  - wget --quiet localhost:8000/api/regions/
  - wget --quiet localhost:8000/api/queries/
  - wget --quiet localhost:8000/api/queryresults/
  - wget --quiet localhost:8000/api/indexentries/
  - wget --quiet localhost:8000/api/events/
  - wget --quiet localhost:8000/api/restarts/
  - wget --quiet localhost:8000/api/workers/
  - wget --quiet localhost:8000/api/system_state/
  - wget --quiet localhost:8000/api/retriever_state/
  - fuser -k 8000/tcp
#  - ./dvactl start &
#  - sleep 420 && docker logs webserver
#  - ./dvactl clean
